#!/bin/bash
# Checks SSL certificate expiration dates for a list of domains.

DOMAINS=("google.com" "baesystems.com")

for DOMAIN in "${DOMAINS[@]}"; do
    echo | openssl s_client -servername "$DOMAIN" -connect "$DOMAIN:443" 2>/dev/null | openssl x509 -noout -dates
done
